/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/carrot/model.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_carrot.geometry} material={materials.orange} />
      <mesh geometry={nodes.Mesh_carrot_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/carrot/model.gltf')
